#ifndef MSGPACK_TYPES_H
#define MSGPACK_TYPES_H

#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>

typedef enum {
    HAZE_RPC_REQUEST = 0,
    HAZE_RPC_RESPONSE = 1,
    HAZE_RPC_NOTIFICATION = 2
} HazeServerRPCType;


typedef enum {
    HAZE_RPC_ERROR_NONE = 0,
    MPACKRPC_MALFORMED_REQ,

    HAZE_RPC_ERROR_PARSE_ERROR,
    HAZE_RPC_ERROR_INVALID_REQUEST,
    HAZE_RPC_ERROR_METHOD_NOT_FOUND,
    HAZE_RPC_ERROR_INVALID_PARAMS,

    HAZE_RPC_ERROR_INTERNAL_ERROR,
    HAZE_RPC_ERROR_SERVER_ERROR,

    HAZE_RPC_ERROR_TIMEOUT,
    HAZE_RPC_ERROR_CONNECTION_CLOSED,

    HAZE_RPC_ERROR_UNKNOWN
} MpackRPCError;


#endif
